import React from 'react';
import styles from '@/styles/Services/WhyWebsiteMatters.module.css';
import {
  RiShieldCheckLine,
  Ri24HoursLine,
  RiSearchLine,
  RiCustomerService2Line,
  RiScales3Line,
  RiGlobalLine
} from 'react-icons/ri';

const cardData = [
  {
    icon: <RiShieldCheckLine className={styles.icon} />,
    title: 'Credibility & Trust',
    highlight: '75%',
    description: "of users judge a company's credibility based on website design.",
    details: 'A professional website establishes trust and legitimacy for your brand in the digital marketplace.'
  },
  {
    icon: <Ri24HoursLine className={styles.icon} />,
    title: '24/7 Availability',
    description: "Your website works for you around the clock, even when you're not working.",
    details: 'Customers can learn about your products and services at any time, from anywhere in the world.'
  },
  {
    icon: <RiSearchLine className={styles.icon} />,
    title: 'SEO Benefits',
    highlight: '93%',
    description: 'of online experiences beginning with a search engine.',
    details: 'An optimized website helps potential customers find you before they find your competitors.'
  },
  {
    icon: <RiCustomerService2Line className={styles.icon} />,
    title: 'Lead Generation',
    highlight: '40%',
    description: 'more leads are generated by websites with contact forms.',
    details: 'Convert visitors into customers with strategic calls-to-action and lead capture mechanisms.'
  },
  {
    icon: <RiScales3Line className={styles.icon} />,
    title: 'Scalability',
    description: 'A well-built website can grow with your business, adapting to changing needs.',
    details: 'From adding new features to handling increased traffic, scalable websites provide long-term value.'
  },
  {
    icon: <RiGlobalLine className={styles.icon} />,
    title: 'Global Reach',
    highlight: '4.9 billion',
    description: 'internet users can be reached globally.',
    details: 'Access international markets and demographics that would be impossible to reach through traditional means.'
  }
];

const WhyWebsiteMatters = () => {
  return (
    <section className={styles.section}>
      <div className={styles.container}>
        <h2 className={styles.heading}>Why Every Business Needs a Great Website</h2>
        <div className={styles.grid}>
          {cardData.map((card, index) => (
            <div key={index} className={styles.card}>
              <div className={styles.iconCircleOuter}>
                <div className={styles.iconCircleInner}>{card.icon}</div>
              </div>
              <h3 className={styles.cardTitle}>{card.title}</h3>
              <p className={styles.cardDescription}>
                {card.highlight && <span className={styles.highlight}>{card.highlight}</span>} {card.description}
              </p>
              <p className={styles.cardDetails}>{card.details}</p>
            </div>
          ))}
        </div>
        <div className={styles.quoteBox}>
          <p className={styles.quote}>
            &quot;A good website isn&apos;t just found — it&apos;s felt. It&apos;s fast, accessible, and built with the user in mind.&quot;
          </p>
        </div>

      </div>
    </section>
  );
};

export default WhyWebsiteMatters;
